cmake_minimum_required(VERSION 3.10)
project(collider_draw_tests LANGUAGES CXX)
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../cmake")
find_package(Maya REQUIRED)
enable_testing()
add_executable(draw_geometry_test draw_geometry_test.cpp)
target_compile_features(draw_geometry_test PRIVATE cxx_std_11)
target_include_directories(draw_geometry_test PRIVATE ../sources "${MAYA_DEVKIT_DIR}/include")
target_compile_definitions(draw_geometry_test PRIVATE ${MAYA_COMPILE_DEFINITIONS})
foreach(library Foundation OpenMaya OpenMayaRender)
    target_link_libraries(draw_geometry_test PRIVATE "${MAYA_DEVKIT_DIR}/lib/${MAYA_LIB_PREFIX}${library}${MAYA_LIB_SUFFIX}")
endforeach()
add_test(NAME draw_geometry COMMAND draw_geometry_test)
